<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>Library</OutputType>
		<UseWPF>true</UseWPF>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<StartupObject />
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CommonServiceLocator" Version="2.0.3" />
		<PackageReference Include="DiscordRichPresence" Version="1.0.175" />
		<PackageReference Include="LightImage.DragDrop.Wpf" Version="0.5.5" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="NVorbis" Version="0.10.5" />
		<PackageReference Include="Prism.Core" Version="9.0.537" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
		<PackageReference Include="System.ServiceModel.NetNamedPipe" Version="8.1.2" />
		<PackageReference Include="Unity" Version="5.11.10" />
		<PackageReference Include="CoreWCF.Http" Version="1.8.0" />
		<PackageReference Include="CoreWCF.NetTcp" Version="1.8.0" />
		<PackageReference Include="CoreWCF.Primitives" Version="1.8.0" />
		<PackageReference Include="CoreWCF.WebHttp" Version="1.8.0" />
	</ItemGroup>
	<ItemGroup>
		<Compile Include="..\Dopamine\SharedAssemblyInfo.cs">
			<Link>SharedAssemblyInfo.cs</Link>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\CSCore.Ffmpeg\CSCore.Ffmpeg.csproj" />
		<ProjectReference Include="..\CSCore\CSCore.csproj" />
		<ProjectReference Include="..\Digimezzo.Foundation.Core\Digimezzo.Foundation.Core.csproj" />
		<ProjectReference Include="..\Digimezzo.Foundation.WPF\Digimezzo.Foundation.WPF.csproj" />
	</ItemGroup>
</Project>