<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <SccProjectName>
    </SccProjectName>
    <SccLocalPath>
    </SccLocalPath>
    <SccAuxPath>
    </SccAuxPath>
    <SccProvider>
    </SccProvider>
    <AssemblyOriginatorKeyFile>..\Dopamine\Dopamine.pfx</AssemblyOriginatorKeyFile>
    <AssemblyTitle>Dopamine.Packager</AssemblyTitle>
    <Product>Dopamine.Packager</Product>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommonServiceLocator" Version="2.0.3" />
    <PackageReference Include="DiscordRichPresence" Version="1.0.175" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Dopamine\SharedAssemblyInfo.cs">
      <Link>SharedAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Include="PackagerConfiguration.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dopamine.Core\Dopamine.Core.csproj" />
  </ItemGroup>
</Project>