<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<OutputType>WinExe</OutputType>
		<WarningLevel>4</WarningLevel>
		<IsWebBootstrapper>false</IsWebBootstrapper>
		<PublishUrl>D:\Documents\Github\Publish\</PublishUrl>
		<Install>true</Install>
		<InstallFrom>Disk</InstallFrom>
		<UpdateEnabled>false</UpdateEnabled>
		<UpdateMode>Foreground</UpdateMode>
		<UpdateInterval>7</UpdateInterval>
		<UpdateIntervalUnits>Days</UpdateIntervalUnits>
		<UpdatePeriodically>false</UpdatePeriodically>
		<UpdateRequired>false</UpdateRequired>
		<MapFileExtensions>true</MapFileExtensions>
		<ApplicationRevision>2</ApplicationRevision>
		<ApplicationVersion>1.0.0.%2a</ApplicationVersion>
		<UseApplicationTrust>false</UseApplicationTrust>
		<PublishWizardCompleted>true</PublishWizardCompleted>
		<BootstrapperEnabled>true</BootstrapperEnabled>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<ApplicationIcon>Dopamine.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ManifestCertificateThumbprint>AE3E50EC2642E6DF871DD1FE119FE44D9424D906</ManifestCertificateThumbprint>
		<ManifestKeyFile>Dopamine_TemporaryKey.pfx</ManifestKeyFile>
		<GenerateManifests>true</GenerateManifests>
		<SignManifests>false</SignManifests>
		<StartupObject>Dopamine.App</StartupObject>
		<Company>Digimezzo</Company>
		<Copyright>Copyright Digimezzo © 2014 - 2022</Copyright>
		<AssemblyVersion>2.0.9.4000</AssemblyVersion>
		<FileVersion>2.0.9.4000</FileVersion>
		<!--<CsWinRTWindowsMetadata>10.0.26100.0</CsWinRTWindowsMetadata>-->
		<InformationalVersion>2.0.9.4000</InformationalVersion>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="System.Windows">
			<HintPath>C:\Program Files (x86)\Windows Kits\10\References\10.0.26100.0\Windows.winmd</HintPath>
			<IsWinMDFile>true</IsWinMDFile>
		</Reference>
	</ItemGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DefineConstants>TRACE;DEBUG;WINDOWS_DESKTOP</DefineConstants>
		<WarningLevel>0</WarningLevel>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
		<PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.26100.4654" />		
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
		<PackageReference Include="System.Management" Version="9.0.8" />
		<PackageReference Include="System.Runtime.WindowsRuntime" Version="4.7.0" />
		<PackageReference Include="CommonServiceLocator" Version="2.0.7" />
		<PackageReference Include="DiscordRichPresence" Version="1.0.175" />
		<PackageReference Include="DryIoc.dll" Version="5.4.3" />
		<PackageReference Include="gong-wpf-dragdrop" Version="3.2.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Prism.Forms.Regions" Version="9.0.537" />
		<PackageReference Include="Prism.Core" Version="9.0.537" />
		<PackageReference Include="Prism.DryIoc" Version="9.0.537" />
		<PackageReference Include="Prism.Wpf" Version="9.0.537" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />
		<PackageReference Include="SQLitePCLRaw.core" Version="3.0.1" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.linux" Version="1.1.14" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.osx" Version="1.1.14" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.v110_xp" Version="1.1.15" />
		<PackageReference Include="CoreWCF.Http" Version="1.8.0" />
		<PackageReference Include="CoreWCF.NetTcp" Version="1.8.0" />
		<PackageReference Include="CoreWCF.Primitives" Version="1.8.0" />
		<PackageReference Include="CoreWCF.WebHttp" Version="1.8.0" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="BaseSettings.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Dopamine.Icons.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Classical.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Club.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Dance.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Full bass.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Full bass and treble.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Full treble.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Headphones.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Large hall.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Live.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Party.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Pop.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Reggae.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Rock.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Ska.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Soft.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Soft rock.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Equalizer\Techno.deq">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<AppDesigner Include="Properties\" />
		<Resource Include="Resources\Fonts\segmdl2.ttf" />
		<Resource Include="Resources\Fonts\Monoglyceride.ttf" />
		<Resource Include="Resources\Fonts\MaterialIcons-Regular.ttf" />
		<Resource Include="Resources\Fonts\fontawesome-webfont.ttf" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="Changelog.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Dopamine.BannerBmp.bmp">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Dopamine.DialogBmp.bmp">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Dopamine.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Dopamine.wxs">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<SubType>Designer</SubType>
		</Content>
		<Content Include="FFmpeg\bin\windows\x64\avcodec-57.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\bin\windows\x64\avformat-57.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\bin\windows\x64\avutil-55.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\bin\windows\x64\swresample-2.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\bin\windows\x86\avcodec-57.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\bin\windows\x86\avformat-57.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\bin\windows\x86\avutil-55.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="FFmpeg\bin\windows\x86\swresample-2.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Aiff.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Dopamine - White.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Dopamine - White.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Dopamine.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Dopamine.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Flac.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Generic.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Legacy tray.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\M3u.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\M4a.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Mp3.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Ogg.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Resource Include="Icons\TaskbarItemInfo_Next.ico" />
		<Resource Include="Icons\TaskbarItemInfo_Pause.ico" />
		<Resource Include="Icons\TaskbarItemInfo_Play.ico" />
		<Resource Include="Icons\TaskbarItemInfo_Previous.ico" />
		<Content Include="Icons\Opus.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Tray_black.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Tray_white.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Wav.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Wma.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Icons\Zpl.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\BG.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\CS.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\DA.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\DE.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\EL.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\EN.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\ES.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\FI.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\FR.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\HR.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\HU.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\ID.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\IT.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\JP.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\KMR.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\KO.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\NL.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\NO.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\PL.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\PT-BR.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\PT-PT.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\RU.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\SR-Cyrl.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\SR-Latn.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\SV.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\TR.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\UK.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\VI.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\ZH-CN.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Languages\ZH-TW.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<SubType>Designer</SubType>
		</Content>
		<Content Include="Libraries\CSCore.dll" />
		<Content Include="Libraries\CSCore.Ffmpeg.dll" />
		<Content Include="Libraries\Digimezzo.Foundation.Core.dll" />
		<Content Include="Libraries\Digimezzo.Foundation.WPF.dll" />
		<Content Include="Libraries\GongSolutions.WPF.DragDrop.dll" />
		<Content Include="Libraries\Ionic.Zip.dll" />
		<Content Include="Libraries\NVorbis.dll" />
		<Content Include="Libraries\System.Windows.Interactivity.dll" />
		<Content Include="Libraries\taglib-sharp.dll" />
		<Content Include="Libraries\WPFFolderBrowser.dll" />
		<Content Include="License.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<BootstrapperPackage Include=".NETFramework,Version=v4.6.1">
			<Visible>False</Visible>
			<ProductName>Microsoft .NET Framework 4.6.1 %28x86 and x64%29</ProductName>
			<Install>true</Install>
		</BootstrapperPackage>
		<BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
			<Visible>False</Visible>
			<ProductName>.NET Framework 3.5 SP1</ProductName>
			<Install>false</Install>
		</BootstrapperPackage>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Digimezzo.Foundation.Core\Digimezzo.Foundation.Core.csproj" />
		<ProjectReference Include="..\Digimezzo.Foundation.WPF\Digimezzo.Foundation.WPF.csproj" />
		<ProjectReference Include="..\Dopamine.Core\Dopamine.Core.csproj" />
		<ProjectReference Include="..\Dopamine.Data\Dopamine.Data.csproj" />
		<ProjectReference Include="..\Dopamine.Packager\Dopamine.Packager.csproj" />
		<ProjectReference Include="..\Dopamine.Services\Dopamine.Services.csproj" />
	</ItemGroup>
</Project>