<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <StartupObject />
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Digimezzo.Foundation.Core\SharedAssemblyInfo.cs">
      <Link>SharedAssemblyInfo.cs</Link>
    </Compile>
    <Resource Include="Effects\FeatheringEffect.ps" />
    <Resource Include="Fonts\MaterialIcons-Regular.ttf" />
    <Resource Include="Fonts\Roboto-Thin.ttf" />
    <Resource Include="Fonts\segmdl2.ttf" />
    <Resource Include="Fonts\fontawesome-webfont.ttf" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Digimezzo.Foundation.Core\Digimezzo.Foundation.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Enums\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Licenses\MahApps.Metro.txt" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Licenses\MaterialDesignInXamlToolkit.txt" />
  </ItemGroup>
</Project>