<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>Library</OutputType>
		<UseWPF>true</UseWPF>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<StartupObject />
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CoreWCF.ConfigurationManager" Version="1.8.0" />
		<PackageReference Include="CoreWCF.Http" Version="1.8.0" />
		<PackageReference Include="CoreWCF.NetTcp" Version="1.8.0" />
		<PackageReference Include="CoreWCF.Primitives" Version="1.8.0" />
		<PackageReference Include="CoreWCF.WebHttp" Version="1.8.0" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="NetCoreServer" Version="8.0.7" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
		<PackageReference Include="System.Management" Version="9.0.8" />
		<PackageReference Include="System.Runtime.Caching" Version="9.0.8" />
		<PackageReference Include="CommonServiceLocator" Version="2.0.3" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Prism.Core" Version="9.0.537" />
		<PackageReference Include="Prism.Wpf" Version="9.0.537" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />
		<PackageReference Include="SQLitePCLRaw.core" Version="3.0.1" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.linux" Version="1.1.14" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.osx" Version="1.1.14" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.v110_xp" Version="1.1.15" />
	</ItemGroup>
	<ItemGroup>
		<Compile Include="..\Dopamine\SharedAssemblyInfo.cs">
			<Link>SharedAssemblyInfo.cs</Link>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\ATL\ATL.csproj" />
		<ProjectReference Include="..\Dopamine.Core\Dopamine.Core.csproj" />
		<ProjectReference Include="..\Dopamine.Data\Dopamine.Data.csproj" />
	</ItemGroup>
</Project>